name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plot:
    concurrency: plot
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: Plot
        run: |
          nix run .#plot
          git add plot.svg
          git add anon.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update plots"
          git push
